[package]
name = "njq"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.4"
snix-eval = { git = "https://github.com/Rucadi/snix", package = "snix-eval" }
serde_json = "1.0.140"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
tempfile = "3.13.0"