[package]
name = "njq"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
tvix-eval = { git = "https://github.com/Rucadi/snix", package = "snix-eval" }

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
tempfile = "3.13.0"